"""initial schema

Revision ID: 96083f11acde
Revises: 
Create Date: 2026-04-22 13:13:47.906215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96083f11acde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sportsbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_commence_time'), ['commence_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_sport_id'), ['sport_id'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=16), nullable=False),
    sa.Column('home_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('away_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spread_or_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_game_book_time', ['game_id', 'sportsbook_id', 'captured_at'], unique=False)

    op.create_table('tracked_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=255), nullable=False),
    sa.Column('odds_at_bet', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_bets_user_id'), ['user_id'], unique=False)

    op.create_table('parlay_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlay_bet_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=255), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['parlay_bet_id'], ['tracked_bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parlay_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parlay_legs_parlay_bet_id'), ['parlay_bet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parlay_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parlay_legs_parlay_bet_id'))

    op.drop_table('parlay_legs')
    with op.batch_alter_table('tracked_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_bets_user_id'))

    op.drop_table('tracked_bets')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_odds_game_book_time')

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_sport_id'))
        batch_op.drop_index(batch_op.f('ix_games_commence_time'))

    op.drop_table('games')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sportsbooks')
    op.drop_table('sports')
    # ### end Alembic commands ###
